[workspace]
authors = ["Daniel Esteban Palma Igor <daniel.palma.i@ug.uchile.cl>"]
channels = ["conda-forge", "bioconda"]
name = "docker-faprotax"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
biom-format = ">=2.1.17,<3"
h5py = ">=3.15.1,<4"
numpy = ">=2.3.5,<3"
